---
title: "**Financial Statement**"
author: 'Created by: EQMarques'
date: "`r Sys.Date()`"
output: html_document
---

```{css, echo=FALSE}
body {
 background-color: white;
    color: darkblue;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(reshape2)
library(tidyverse)
library(scales)
library(ggplot2)

#df = read.csv(file.choose())
df = readxl::read_excel("Money_balance.xlsx")
df$grp = c("a")

df$Salary = as.numeric(df$Salary)
df$Valued_stuff = as.numeric(df$Valued_stuff)
df$bank = as.numeric(df$bank)
df$all = as.numeric(df$all)
df$Date = as.Date(df$Date, "%m/%d/%Y")
```
## Money in Assets and Bank
```{r bank, echo=FALSE}

ggplot(df, aes(x=Date, y = all))+
  geom_line(aes(group = grp), size = 1)+
  geom_point(size = 2)+
  theme_bw()+
  labs(y = NULL, x = NULL, title = "Total assets")+
    annotate(geom="text", x=df$Date[length(df$Date)-1],
           y=max(df$all)+3000,
           label= round(df$all[length(df$all)], 0),
           color = "darkgreen", size = 5)+
  theme(plot.title = element_text(hjust = 0.5), 
        axis.text.x = element_text(angle = 90),
        legend.position = "none")



ggplot(df, aes(x=Date, y = bank))+
  geom_line(aes(group = grp), size = 1)+
  geom_point(size = 2)+
  theme_minimal()+
  labs(y = NULL, x = NULL, title ="Total Money in bank")+
  annotate(geom="text", x=df$Date[length(df$Date)-1],
           y=max(df$bank)+1000,
           label= round(df$bank[length(df$bank)], 0),
           color = "darkblue", size = 5)+
  ylim(min(df$bank), max(df$bank)+2000)+
  theme(plot.title = element_text(hjust = 0.5), 
        axis.text.x = element_text(angle = 90),
        legend.position = "none")
```

## Total Money in bank and other goods with values
```{r Total, echo=FALSE}
#Percentage graph
perc = df %>% 
  select(bank, all, Valued_stuff, Date)

perc$bank = signif((perc$bank/perc$all)*100, digits = 2)
perc$Valued_stuff = signif((perc$Valued_stuff/perc$all)*100, digits = 2)

perc2 = perc %>% select(bank, Valued_stuff, Date)
perc2 = tail(perc2, n =1)
perc2 = melt(perc2, id = "Date")

note = df %>% 
  select(bank, Valued_stuff)
note = tail(note, n =1)
note = melt(note)
note$value = signif(note$value, digits = 2)/1000


ggplot(perc2, aes(x=value, y=variable, fill = variable))+
  geom_col()+
  geom_text(aes(x = value, label = paste0(value, "% (", note$value, " mil R$)")), color = "black", size=4, hjust = -0.1) +
  scale_fill_manual(values = c("darkblue","darkred"))+
  labs(y = NULL, x = NULL, title = "Proportion of money")+
  theme_bw()+
  xlim(0, max(perc2$value + 20))+
  theme(legend.position = "None")

```

## Money in material speculations
```{r stuff, echo=FALSE}
ggplot(df, aes(x=Date, y=Valued_stuff))+
  geom_area(fill = "blue", alpha = 0.55)+
  theme_bw()+
  labs(x = NULL, y = "Reais")+
  theme(plot.title = element_text(hjust = 0.5), 
        axis.text.x = element_text(angle = 90))
```

## Salary
```{r salary, echo=FALSE}
ggplot(df, aes(x=Date, y=Salary))+
  geom_area(fill = "darkgreen", alpha = 0.55)+
  theme_bw()+
  labs(x = NULL, y = "Reais")+
  theme(plot.title = element_text(hjust = 0.5), 
        axis.text.x = element_text(angle = 90))
```